---
- name: Port Error Disabled Check
  hosts: switches
  gather_facts: false

  tasks:
  - name: 'List which ports were err-disabled'
    cisco.ios.ios_command:
      commands:
        - show int status err-dis
    register: output

  - name: Display result
    ansible.builtin.debug:
      var: output.stdout_lines
